let modeloJson = [
    {
      id: 1,
      name: 'Camiseta Preta',
      img: 'img/1.png',
      price: 20.19,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 2,
      name: 'Camiseta vermelha',
      img: 'img/2.png',
      price: 18.0,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 3,
      name: 'Camiseta Laranja',
      img: 'img/3.png',
      price: 17.45,
      sizes: ['dry', 'malha', 'algodão'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 4,
      name: 'Camiseta Branca',
      img: 'img/4.png',
      price: 19.77,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 5,
      name: 'Camiseta Branca 2',
      img: 'img/5.png',
      price: 21.43,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 6,
      name: 'Camiseta Laranja 2',
      img: 'img/6.png',
      price: 18.55,
      sizes: ['malha', 'dry', 'algodão'],
      description: 'Blusa Básica Manga Curta',
    },
  ];